import { BakeryItem, Review } from './types';

// Import local images as ES modules so Vite can bundle them and resolve correct production paths
import smurfberryCake from './assets/images/smurfberry_cake_1780053259348.png';
import smurfetteBlueCake from './assets/images/smurfettebluecake.png';
import smurfoTruffle from './assets/images/smurfo_truffle_1780053842811.png';
import hotCocoaMarshmallowCake from './assets/images/hot_cocoa_marshmallow_cake_1780054086796.png';
import enchantedForestBlueMuffin from './assets/images/enchanted_forest_blue_muffin_1780054106538.png';
import snowyVanillaCustardCake from './assets/images/snowy_vanilla_custard_cake_1780054122695.png';
import mushroomTart from './assets/images/mushroom_tart_1780053861465.png';
import smurfetteCupcake from './assets/images/smurfette_cupcake_1780053880612.png';

// Let's use the local paths for the generated images
export const SIGNATURE_CAKES: BakeryItem[] = [
  {
    id: 'cake-smurfberry-dream',
    name: 'Smurfberry Dream Cake',
    category: 'cakes',
    description: 'A masterpiece tier-cake infused with glowing winter smurfberries, rich white velvet cream frosting, and sparkling fairy dust candies.',
    price: 34.99,
    rating: 5.0,
    image: smurfberryCake,
    tags: ['Cozy Sweetness', 'Magical Glow', 'House Special'],
  },
  {
    id: 'cake-blueberry-cheesecake',
    name: 'Glistening Blueberry Cheesecake',
    category: 'cheesecakes',
    description: 'Light, silky smooth premium cheesecake crust topped with glowing icy blue berry nectar glaze and sugar crystals.',
    price: 24.99,
    rating: 4.9,
    image: smurfetteBlueCake,
    tags: ['Icy Glaze', 'Fairy Crust', 'Gourmet'],
  },
  {
    id: 'cake-chocolate-truffle',
    name: 'Belgian Chocolate Smurfo-Truffle',
    category: 'cakes',
    description: 'Deep midnight-blue cocoa cake layers, rich chocolate ganache, and soft, glowing edible silver sparkles from the enchanted cavern.',
    price: 29.99,
    rating: 4.8,
    image: smurfoTruffle,
    tags: ['Rich Dark', 'Enchanted Cocoa', 'Glow dust'],
  },
  {
    id: 'cake-marshmallow-hotcoco',
    name: 'Hot Chocolate Marshmallow Cake',
    category: 'cakes',
    description: 'Cozy spiced chocolate sponge layered with hot cocoa mousse, topped with charred campfire-style vanilla marshmallows.',
    price: 26.99,
    rating: 4.7,
    image: hotCocoaMarshmallowCake,
    tags: ['Spiced Warm', 'Melted Snow', 'Cozy Vibe'],
  },
  {
    id: 'cake-oreo-frost',
    name: 'Icy Oreo Frost Cake',
    category: 'cakes',
    description: 'Crunchy crushed black cookie biscuits layers embedded in glowing cream cheese icing that tastes like the first winter blizzard.',
    price: 25.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    tags: ['Blizzard Frost', 'Crunchy Snow'],
  },
  {
    id: 'cake-strawberry-vanilla',
    name: 'Strawberry Vanilla Snow Cake',
    category: 'cakes',
    description: 'Chilled sponge layers infused with local forest wild-sweet strawberries covered in a cloud of fluffy chantilly cream.',
    price: 27.99,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=600&q=80',
    tags: ['Winter Berry', 'Whipped Snow', 'Pastel Blush'],
  },
  {
    id: 'cake-winterberry-revelry',
    name: 'Gilded Winterberry Frost Cake',
    category: 'cakes',
    description: 'A rich double-tier spiced sponge cake smothered in frosted sapphire syrup, garnished with sweet glowing redcurrants and magic glaze drops.',
    price: 28.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80',
    tags: ['Frosted Gold', 'Winter Spiced', 'Royal Gloss'],
  },
  {
    id: 'cake-snowy-chestnut-hazel',
    name: 'Cozy Snowy Chestnut Log',
    category: 'cakes',
    description: 'Smurf-village traditional winter log rolled with silky hazelnut butter, dusted with sweet powdered white cocoa snow.',
    price: 29.99,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    tags: ['Hazelnut Butter', 'Mushroom Hearth', 'Holiday Joy'],
  }
];

export const TREATS: BakeryItem[] = [
  {
    id: 'treat-snowy-brownie',
    name: 'Fudge Snowy Brownie',
    category: 'brownies',
    description: 'Warm, gooey molten Belgian cocoa brownie topped with standard frosting drips and glowing candy pearls.',
    price: 6.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    tags: ['Molten Cocoa', 'Warm Hearth'],
  },
  {
    id: 'treat-forest-muffin',
    name: 'Enchanted Forest Blue Muffin',
    category: 'muffins',
    description: 'Freshly baked muffin bursting with hot sweet smurfberries, glowing blue glaze, and a dusting of magic snow powder.',
    price: 5.49,
    rating: 4.8,
    image: enchantedForestBlueMuffin,
    tags: ['Fresh Baked', 'Smurfberry Core'],
  },
  {
    id: 'treat-mint-cupcake',
    name: 'Winter Icy Mint Cupcake',
    category: 'treats',
    description: 'Refreshing frosty cool organic mint cream swirl on top of fluffy midnight black cocoa sponge.',
    price: 4.99,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80',
    tags: ['Cool Mint', 'Glowing Sparkle'],
  },
  {
    id: 'treat-gingerbread-cookie',
    name: 'Smurfy Ginger Forest Cookie',
    category: 'treats',
    description: 'Spiced ginger winter cookie baked in the shape of miniature forest animals and village mushroom chimneys.',
    price: 3.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=600&q=80',
    tags: ['Spiced Cinnamon', 'Cozy Warmth'],
  },
  {
    id: 'treat-snowy-pops',
    name: 'Snowy Forest Cake Pop',
    category: 'treats',
    description: 'Magical blue velvet cake pops with bright white chocolate shells and sparkling stars on top.',
    price: 4.49,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&w=600&q=80',
    tags: ['Candy Crunch', 'Fairy Swirl'],
  },
  {
    id: 'brownie-mint-swirl',
    name: 'Sparkling Mint Swirl Brownie',
    category: 'brownies',
    description: 'Fudgy white chocolate and dark cocoa brownie base layered with an icy-mint green glaze and glowing blue nonpareils.',
    price: 6.49,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    tags: ['Fudgy White', 'Mint Glow', 'Cool Frost'],
  },
  {
    id: 'brownie-salted-snow-caramel',
    name: 'Glazed Snow Caramel Brownie',
    category: 'brownies',
    description: 'A decadent caramelized brownie base with crystallized winter salt and rich blue-butter caramel toppings.',
    price: 6.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80',
    tags: ['Cozy Salted', 'Butterscotch Caramel'],
  },
  {
    id: 'muffin-snow-crystallized',
    name: 'Crystallized Snow Peach Muffin',
    category: 'muffins',
    description: 'Soft vanilla peach muffin filled with warm sweet peach jam and capped with crystalline sugar icing sparkles.',
    price: 5.99,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80',
    tags: ['Peach Jam', 'Crystalline Sugars'],
  },
  {
    id: 'muffin-spiced-cranberry',
    name: 'Spiced Cranberry Glow Muffin',
    category: 'muffins',
    description: 'Zesty spiced orange muffin featuring vibrant, plump tart winter cranberries and a drizzle of sparkly cream cheese.',
    price: 5.49,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80',
    tags: ['Zesty Orange', 'Tart Cranberry', 'Holiday Vibe'],
  },
  {
    id: 'treat-smurfy-marshmallow-pop',
    name: 'Glowy Smurfy Cocoa-pop',
    category: 'treats',
    description: 'Giant soft blue marshmallow dip-coated in local honey hazelnut sauce and sparkling silver edible flakes.',
    price: 4.99,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&w=600&q=80',
    tags: ['Hazelnut Glaze', 'Blue Flakes', 'Double Sweet'],
  },
  {
    id: 'treat-cozy-cinnamon-star',
    name: 'Starry Cinnamon Winter Biscuit',
    category: 'treats',
    description: 'Spiced buttery shortbread star with an elegant blue royal icing swirl and a sparkling edible gem in the center.',
    price: 3.49,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=600&q=80',
    tags: ['Royal Icing', 'Sweet Butter', 'Starry Crust'],
  }
];

export const CHEESECAKES: BakeryItem[] = [
  {
    id: 'cheese-vanilla-bean',
    name: 'Snowy Vanilla Bean Custard Cake',
    category: 'cheesecakes',
    description: 'Creamy Madagascar vanilla bean cheesecake decorated with beautiful sugar snowflake sculptures and glistening peaks.',
    price: 23.99,
    rating: 4.8,
    image: snowyVanillaCustardCake,
    tags: ['Bourbon Vanilla', 'Smooth Frost'],
  },
  {
    id: 'cheese-glowberry-swirl',
    name: 'Glow Berry Swirl Cheesecake',
    category: 'cheesecakes',
    description: 'A smooth fantasy cheesecake ribboned with glowing sapphire elderberries and standard wild blueberry purees.',
    price: 26.50,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    tags: ['Organic Swirl', 'Magic Ripples'],
  },
  {
    id: 'cheese-icy-caramel',
    name: 'Icy Caramel Crunch Cheesecake',
    category: 'cheesecakes',
    description: 'Cold cream-cheese baseline, drenched in hand-spun cold golden caramel and crystallized premium sea salt particles.',
    price: 24.99,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1508737027454-e6454ef45afd?auto=format&fit=crop&w=600&q=80',
    tags: ['Salty Sweet', 'Caramel Glass'],
  },
  {
    id: 'cheese-cloudberry-aurora',
    name: 'Aurora Cloudberry Cheesecake',
    category: 'cheesecakes',
    description: 'Infused with golden, rare Scandinavian forest cloudberries and topped with a shimmering violet sugar lace dome.',
    price: 25.99,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1508737027454-e6454ef45afd?auto=format&fit=crop&w=600&q=80',
    tags: ['Cloudberry Nectar', 'Aurora Glow', 'Dreamy Cream'],
  },
  {
    id: 'cheese-cozy-maple-pecan',
    name: 'Cozy Maple Pecan Ice-slice',
    category: 'cheesecakes',
    description: 'Velvety maple syrup-infused cream cheese topped with light roasted spiced maple pecans and frosted white sugar drizzle.',
    price: 24.50,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    tags: ['Maple Roasted', 'Crunchy Pecans', 'Winter Cozy'],
  }
];

export const SMURF_SPECIALS: BakeryItem[] = [
  {
    id: 'smurf-mushroom-cake',
    name: 'Papa Smurf’s Magic Mushroom Tart',
    category: 'specials',
    description: 'A whimsical red-and-white-spotted wild berry tart with a glowing blue crust that gives you a burst of energy!',
    price: 12.99,
    rating: 5.0,
    image: mushroomTart,
    tags: ['Papa’s Elixir', 'Blueberries & Raspberries', 'Legendary'],
    isSmurfSpecial: true,
  },
  {
    id: 'smurf-smurfette-delight',
    name: 'Smurfette’s Pastel Frosting Swirl',
    category: 'specials',
    description: 'A magical light blue chocolate cupcake decorated with beautiful spun sugar flower petals and silver edible pearls.',
    price: 8.99,
    rating: 4.9,
    image: smurfetteCupcake,
    tags: ['Fairy Swirl', 'Dahlia Pastel', 'Very Cute'],
    isSmurfSpecial: true,
  },
  {
    id: 'smurf-snowy-donut',
    name: 'Snowy Glow Donut Tower',
    category: 'specials',
    description: 'Glistening light-blue frosted miniature forest yeast donuts stacked as a cute snowy pyramid model with sparklers on top.',
    price: 15.99,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
    tags: ['Donut Tower', 'Glazed Winter', 'Shareable'],
    isSmurfSpecial: true,
  },
  {
    id: 'smurf-dessert-jar',
    name: 'Brainy Smurf’s Magic Frosting Jar',
    category: 'specials',
    description: 'Layered organic cream cheese, sweet wild smurfberry compote, and blue sugar dust encased in a mystical vintage forest glass vial.',
    price: 10.49,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=600&q=80',
    tags: ['Jar Pudding', 'Smurfberry Dust', 'Brainy Idea'],
    isSmurfSpecial: true,
  },
  {
    id: 'smurf-harmony-punch',
    name: 'Harmony’s Frosted Punch Parfait',
    category: 'specials',
    description: 'A dreamy layered dessert containing dynamic blue curaçao pudding, vanilla sponge crumbs, and a crisp, cold white sugar star canopy.',
    price: 11.99,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=600&q=80',
    tags: ['Curaçao Frost', 'Sugar Stars', 'Melodious Cup'],
    isSmurfSpecial: true,
  },
  {
    id: 'smurf-joky-box-cookie',
    name: 'Joky Smurf’s Surprise Cookie Box',
    category: 'specials',
    description: 'A crisp puff-pastry cube that reveals a sweet, warm, gooey hot-fudge center once bitten. Watch out for the delicious sprinkles explosion!',
    price: 11.49,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&w=600&q=80',
    tags: ['Surprise Center', 'Cream Explosion', 'Prankster Delight'],
    isSmurfSpecial: true,
  }
];

export const ALL_BAKERY_ITEMS: BakeryItem[] = [
  ...SIGNATURE_CAKES,
  ...TREATS,
  ...CHEESECAKES,
  ...SMURF_SPECIALS,
];

export const COZY_TESTIMONIALS: Review[] = [
  {
    id: 'rev-1',
    name: 'Brainy Smurf',
    role: 'Village Smartguy',
    comment: 'The Smurfberry Dream Cake is mathematically perfect. The ratio of frosty sweetness to forest berry tartness is exactly 1.618! My highly sophisticated tastebuds approve!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    date: 'Dec 12, 2025'
  },
  {
    id: 'rev-2',
    name: 'Smurfette',
    role: 'Village Dreamer',
    comment: 'It is simply enchanting! Every bite feels like a beautiful slow-motion stroll through the first winter snow. The Glistening Blueberry Cheesecake makes all my fairy wishes come true!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    date: 'Jan 05, 2026'
  },
  {
    id: 'rev-3',
    name: 'Papa Smurf',
    role: 'Head of Village & Magic',
    comment: 'Indeed, my little Smurfs! I have infused an extra pinch of glowing forest enchantment, but the bakery team’s cozy hospitality is what makes this warm bakery truly magical.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    date: 'Feb 14, 2026'
  }
];
